version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    depends_on: 
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app